### ISSUE TITLE
Photo gallery view 

### ISSUE THREAD

**Issue by Jarami110d** [a-thousand-channels/ORTE-backend#123]
When I choose a Map and a Layer and want to look a the images and photos of a specific Orte, I want to be able to navigate through all pictures without having to exit the extended view of a single image.
![Screenshot 2021-10-16 at 16 30 25](https://user-images.githubusercontent.com/89705792/137591463-b6a1fa3d-4a15-4dcf-8235-eeb16ff3e224.jpg)
.

**Comment by ut** [comment]
Hey, cool, we'll need this!

**Comment by Sefux** [comment]
Photo gallery was added on show view
