### ISSUE TITLE
Error when trying to edit already uploaded pictures to a mapped place.

### ISSUE THREAD

**Issue by Jarami110d** [a-thousand-channels/ORTE-backend#136]
When I open the entry of any mapped place an have uploaded an Image, if I want to go back and edit, for example change the name or set as preview, its not possible to access the edit page, when clicking on the edit symbol and an error occurs.

**Comment by ut** [comment]
Thanks. It seems that the linking of the edit button is wrong since we have speaking urls. I'll can fix it!

**Comment by Jarami110d** [comment]
Image Edit function works again! Merci.

**Comment by ut** [comment]
Thanks for testing!
