### ISSUE TITLE
Feature tests: Stub remote base layer calls...

### ISSUE THREAD

**Issue by ut** [a-thousand-channels/ORTE-backend#151]
....like https://api.mapbox.com

**Comment by ut** [comment]
... in spec_helper.rb > line 50

**Comment by Sefux** [comment]
In spec_helper.rb a new stub_request for api.mapbox.com is needed

**Comment by ut** [comment]
I've fixed the specs today. Additionally, the mapbox call needs a token. Since the rendering of this baselayer doesnt play a role in feature testing, the call is now skipped in test environments
