### ISSUE TITLE
Safari can´t Load Map at staging.orte.link

### ISSUE THREAD

**Issue by Jarami110d** [a-thousand-channels/ORTE-backend#193]
After successful log-in at https://staging.orte.link on Safari... its not possible to load any Map content. 

None of the Maps are displayed. Map area shows completely Gray.

**Comment by ut** [comment]
I can confirm, possibly the action cable (websockets) calls break the javascript ("Refused to connect to wss://... because it does not appear in the connect-src directive of the Content Security Policy.")

**Comment by ut** [comment]
Plus: Safari has a problem with websockets, rails-style:  https://github.com/rails/rails/issues/43835

**Comment by Sefux** [comment]
Fixed in #194 
@Jarami110d can you test it on safari

**Comment by Jarami110d** [comment]
Yeah! Staging is working again on Safari! 👍

**Comment by ut** [comment]
Yeah :)
