### ISSUE TITLE
Settings with config_for

### ISSUE THREAD

**Issue by ut** [a-thousand-channels/ORTE-backend#251]
Follow up for Settingslogic setting (Settingslogic Gem ist outdated and not Ruby 3 ready)

**Comment by Sefux** [comment]
There are still some Settings errors in production/staging env.
To test these run:

`RAILS_ENV=production bundle exec rake middleware`

**Comment by ut** [comment]
Ah thanks. It seems that with 6 settings w/Settingslogic will not be loaded in the environment files anymore. 

I think this relates to #250 I'll fix it there.

**Comment by ut** [comment]
Removed settingslogic, while prepare to bump Ruby version to 3.  @Sefux if you want to adapt, see #278
